'use client';

import { FormEvent, useState } from 'react';
import { useRouter } from 'next/navigation';

export default function LoginPage() {
  const router = useRouter(); const [email,setEmail]=useState(''); const [code,setCode]=useState(''); const [sent,setSent]=useState(false); const [message,setMessage]=useState(''); const [busy,setBusy]=useState(false);
  async function send() { setBusy(true); setMessage(''); const response=await fetch('/api/admin/auth/otp',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email})}); const json=await response.json(); setBusy(false); if(!response.ok){setMessage(json.error?.message??'发送失败');return;} setSent(true); setMessage('验证码已发送，请查收邮箱。'); }
  async function submit(event:FormEvent) { event.preventDefault(); setBusy(true); const response=await fetch('/api/admin/auth/verify',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email,code})}); const json=await response.json(); setBusy(false); if(!response.ok){setMessage(json.error?.message??'验证失败');return;} router.push('/admin'); }
  return <main className="admin-login-page"><section className="admin-login-panel"><div className="admin-login-brand"><span className="admin-login-mark">C</span><span>ChongHub Operations</span></div><span className="admin-eyebrow">运营后台 · 管理员入口</span><h1>欢迎回到运营工作台</h1><p className="admin-login-lede">在这里处理订单履约、更新商品状态，并跟进客户售后请求。</p><form className="admin-login-form" onSubmit={submit}><label>管理员邮箱<input type="email" required autoComplete="email" value={email} onChange={(e)=>setEmail(e.target.value)} placeholder="admin@company.com" /></label><div className="admin-login-code"><label>邮箱验证码<input inputMode="numeric" pattern="[0-9]{6}" required={sent} value={code} onChange={(e)=>setCode(e.target.value)} placeholder="输入 6 位验证码" /></label><button className="admin-send-code" type="button" onClick={send} disabled={busy || !email}>{sent?'重新发送':'发送验证码'}</button></div>{message&&<p className="admin-login-message">{message}</p>}<button className="admin-login-submit" type="submit" disabled={busy || !sent}>{busy?'处理中…':'进入管理后台'}</button></form><p className="admin-login-note">仅限授权运营人员使用 · 操作将记录在审计日志中</p></section><aside className="admin-login-aside"><span className="admin-aside-kicker">TODAY&apos;S OPERATIONS</span><strong>让每一笔订单<br />都有明确进展</strong><div className="admin-aside-items"><span>订单处理</span><span>商品状态</span><span>售后跟进</span></div></aside></main>;
}
