'use client';

import { FormEvent, useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import type { ProductView } from '@/modules/catalog/contracts';

export default function NewRequestPage() {
  const router=useRouter(); const [products,setProducts]=useState<ProductView[]>([]); const [skuId,setSkuId]=useState(''); const [email,setEmail]=useState(''); const [subscription,setSubscription]=useState('free'); const [note,setNote]=useState(''); const [message,setMessage]=useState(''); const [busy,setBusy]=useState(false);
  useEffect(()=>{const requestedSku = new URLSearchParams(window.location.search).get('skuId'); fetch('/api/products').then((r)=>r.json()).then((json)=>{const list: ProductView[] = json.data??[];setProducts(list);const available = list.flatMap((product)=>product.skus).some((sku)=>sku.id===requestedSku);setSkuId(available ? requestedSku! : list[0]?.skus[0]?.id??'');}).catch(()=>setMessage('商品暂时无法加载，请稍后重试。'));},[]);
  async function submit(event:FormEvent){event.preventDefault();setBusy(true);setMessage('');const response=await fetch('/api/orders',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({skuId,contactEmail:email,declaredSubscription:subscription,note,idempotencyKey:crypto.randomUUID()})});const json=await response.json();setBusy(false);if(!response.ok){setMessage(json.error?.message??'提交失败');return;}router.push(`/requests/${json.data.number}/screening`);}
  return <main className="content-page"><section className="container narrow-page"><span className="eyebrow">提交需求</span><h1>先提交需求，再完成初筛</h1><p className="page-lede">游客也可以提交。我们不会在这里收取在线支付，后续由微信客服人工确认。</p><form className="form-card" onSubmit={submit}><label>选择套餐<select value={skuId} onChange={(e)=>setSkuId(e.target.value)} required>{products.flatMap((product)=>product.skus.map((sku)=><option key={sku.id} value={sku.id}>{product.name} · {sku.name} · ¥{(sku.priceCents/100).toFixed(0)}</option>))}</select></label><label>联系邮箱<input type="email" required value={email} onChange={(e)=>setEmail(e.target.value)} placeholder="用于接收进度通知和游客查单验证码" /></label><label>当前订阅情况<select value={subscription} onChange={(e)=>setSubscription(e.target.value)}><option value="free">当前无有效订阅</option><option value="subscribed">当前正在订阅</option><option value="unknown">不确定</option></select></label><label>补充说明（可选）<textarea maxLength={2000} value={note} onChange={(e)=>setNote(e.target.value)} placeholder="不要填写 ChatGPT 会话内容、令牌或密码。" /></label>{message&&<p className="form-message">{message}</p>}<button className="button button-primary" type="submit" disabled={busy||!skuId}>{busy?'提交中…':'提交需求并开始初筛'}</button></form></section></main>;
}
